name: Linter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: type:check
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format:check
